name: Build Android App

on:
  push:
    branches:
      - main

env:
  ANDROID_SDK_TOOLS: /usr/local/android-sdk/tools
  ANDROID_HOME: /usr/local/android-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Android SDK
      uses: nir0s/setup-android-sdk@v2
      with:
        sdk_license: accept
        components: tools,platform-tools,build-tools;28.0.3,android-28

    - name: Install dependencies
      run: ./gradlew install

    - name: Build app
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
